### ISSUE TITLE
Plan for releasing data

### ISSUE THREAD

**Issue by wjhou** [hegehongcha/LaymanRRG#3]
Hi, 

Thanks for your contributions and it is impressive. Do you have any plans for releasing the dataset?

Best,
Ethan

**Comment by gowitheflow-1998** [comment]
@wjhou Hi Ethan. Thanks! We do have a plan of releasing the dataset in the coming month!

**Comment by wjhou** [comment]
Thank you. Looking forward to it.

**Comment by gowitheflow-1998** [comment]
@wjhou Hi Ethan, our 50k report-level dataset is released at: https://huggingface.co/datasets/LaymanRRG/LaymanRRG-report-level with reports translated into layman's terms and corresponding image IDs from mimic. This dataset can be used to train the models in the paper, in case it'll be useful for you already! We will release the sentence-level dataset to enhance evaluation soon as well.

**Comment by wjhou** [comment]
Thank you so much. Will conduct some experiments on it. 👍
